---
- name: Test Condizionali
  hosts: rocky9
  become: true
  
  tasks:
    - name: Verifica famiglia del sistema operativo
      ansible.builtin.debug:
        msg: "Il sistema operativo è basato su= {{ ansible_facts['os_family'] }}"
    - name: 2. Esegui la task solo se il sistema operativo è basato su RedHat
      ansible.builtin.debug:
        msg: "Siamo su Rocky Linux 9, che è basato su RedHat!"
      when: ansible_facts['os_family'] == "RedHat"
    - name: 3. Esegui la task solo se il sistema operativo è basato su Debian
      ansible.builtin.debug:
        msg: "Siamo su un sistema basato su Debian!"
      when: ansible_facts['os_family'] == "Debian" 