apiVersion: v1
data:
  password: UGFzc3dvcmQ=
  username: VXNlcg==
kind: Secret
metadata:
  creationTimestamp: "2026-07-07T12:43:19Z"
  name: new-credentials
  namespace: default
  resourceVersion: "11512"
  uid: 23f3a348-2110-44ef-8beb-66797a2c24eb
type: Opaque
