apiVersion: v1
kind: Pod
metadata:
  name: my-first-pod
spec:
  restartPolicy: Never
  containers:
    - name: my-first-container
      image: alpine
      command: ["sh", "-c", "while true; do sleep 3600; done"]
      env:
        - name: CRED_USER
          valueFrom:
            secretKeyRef:
              name: dev-credentials
              key: username
        - name: PASS_USER
          valueFrom:
            secretKeyRef:
              name: dev-credentials
              key: password
