def imageTag = '' 

pipeline {
    agent {
        label 'linux-agent'
    }

    environment {
        DOCKER_HUB_USER = 'schioppolone'
        IMAGE_NAME      = 'flask-app-example'
        DOCKER_REGISTRY = "docker.io/${DOCKER_HUB_USER}/${IMAGE_NAME}"
        DOCKER_CREDS_ID = 'dockerhub-credentials'
    }

    stages {
        stage('Calcolatore Tag') {
            steps {
                script {
                    if (env.TAG_NAME) {
                        imageTag = env.TAG_NAME
                        echo "Tag Git Rilevato: [${env.TAG_NAME}] - Utilizzato dall'immagine Docker"    
                    } else if (env.BRANCH_NAME == 'master' || env.BRANCH_NAME == 'main') {
                        imageTag = 'latest'
                        echo "Branch principale [${env.BRANCH_NAME}] rilevato - Immagine Docker taggata come [latest]"
                    } else if (env.BRANCH_NAME == 'develop') {
                        def commitSha = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
                        imageTag = "develop-${commitSha}"
                        echo "Branch Develop Rilevato - Immagine Docker taggata come '${imageTag}'."
                    }
                }
            }
        }

        stage('Docker Build') {
            steps {
                script {
                    echo "Costruzione immagine Docker: ${DOCKER_REGISTRY}:${imageTag}"
                    dir('Pipeline_Jenkins_Dichiarativa/app') {
                        sh "docker build -t ${DOCKER_REGISTRY}:${imageTag} ."
                    }
                }
            }
        }

        stage('Docker Push') {
            steps {
                script {
                    docker.withRegistry("https://index.docker.io/v1/", DOCKER_CREDS_ID) {
                        echo "Push su Docker Hub..."
                        dir('Pipeline_Jenkins_Dichiarativa/app') {
                            sh "docker push ${DOCKER_REGISTRY}:${imageTag}"
                        }
                    }
                }
            }
        }

        stage('Cleanup') {
            steps {
                script {
                    echo 'Cleaning up local image from agent...'
                    sh "docker rmi ${DOCKER_REGISTRY}:${imageTag} || true"
                }
            }
        }
    }
}