Vagrant.configure("2") do |config|
    config.vm.box = "generic/rocky9"
    config.vm.define "rocky9_server" do |subconfig|
        subconfig.vm.network "private_network", ip: "172.16.1.10"
        subconfig.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = 1
            vb.name = "Rocky9_Ansible_Lab"
        end
    end
end
