Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9"
  config.vm.box_version = "4.3.12"
  config.vm.hostname = "jenkins-k8s-lab"
  
  config.vm.network "private_network", ip: "192.168.56.10"
  

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./deploy.yml"
    ansible.become = true
    ansible.extra_vars = {
      jenkins_agent_secret: ENV['JENKINS_AGENT_SECRET']
    }
  end

  
  config.vm.provider "virtualbox" do |v|
    v.name = "Rocky9_Lab"
    v.memory = 2048
    v.cpus = 2
  end
end